import { StyleSheet } from 'react-native';
import { colors, fontFamily, fontFamilyMedium } from '../../ui';

export const styles = StyleSheet.create({
  root: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 34 },
  promptCard: {
    marginTop: 9,
    padding: 18,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    elevation: 3,
  },
  promptHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  promptIndex: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.wine,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promptIndexText: {
    fontFamily,
    color: colors.goldSoft,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
  },
  promptHeaderText: { flex: 1 },
  promptTitle: {
    fontFamily: fontFamilyMedium,
    color: colors.ink,
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  example: { fontFamily, color: colors.inkSoft, fontSize: 11, lineHeight: 17, marginTop: 4 },
  field: { width: '100%', minHeight: 120, textAlignVertical: 'top' },
  confirmTopic: {
    marginTop: 10,
    minHeight: 42,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.wine,
    borderWidth: 1,
    borderColor: colors.goldDark,
  },
  confirmTopicDone: { backgroundColor: '#A30F60' },
  confirmTopicText: {
    fontFamily: fontFamilyMedium,
    color: colors.lightText,
    fontSize: 11,
    fontWeight: '800',
  },
  confirmTopicTextDone: { color: colors.white },
  disabled: { opacity: 0.42 },
  pressed: { opacity: 0.82 },
  analysisPanel: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 12,
  },
  analysisTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  analysisLabel: {
    fontFamily: fontFamilyMedium,
    color: colors.wine,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  analysisMuted: { fontFamily, color: colors.inkMuted, fontSize: 9 },
  analysisDivider: { height: 1, backgroundColor: colors.border, marginVertical: 9 },
  categoryRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  categoryCopy: { flex: 1 },
  categoryCaption: { fontFamily, color: colors.inkMuted, fontSize: 9 },
  categoryValue: {
    fontFamily: fontFamilyMedium,
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  manualBadge: {
    fontFamily,
    color: colors.magenta,
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 1,
    marginTop: 4,
  },
  categoryButton: {
    minHeight: 36,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.goldDark,
    borderRadius: 8,
  },
  categoryButtonText: {
    fontFamily: fontFamilyMedium,
    color: colors.wine,
    fontSize: 9,
    fontWeight: '800',
  },
  suggestionCard: {
    marginTop: 12,
    padding: 15,
    borderRadius: 12,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  suggestionGoldLine: { width: 42, height: 2, backgroundColor: colors.gold, marginBottom: 9 },
  suggestionEyebrow: {
    fontFamily: fontFamilyMedium,
    color: colors.wine,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  suggestionText: {
    fontFamily,
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    marginTop: 5,
  },
  suggestionActions: { marginTop: 12, flexDirection: 'row', gap: 8 },
  useSuggestionButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: colors.wine,
  },
  useSuggestionText: {
    fontFamily: fontFamilyMedium,
    color: colors.lightText,
    fontSize: 9,
    fontWeight: '800',
  },
  ignoreButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  ignoreText: {
    fontFamily: fontFamilyMedium,
    color: colors.inkSoft,
    fontSize: 9,
    fontWeight: '800',
  },
  sectionSpacer: { height: 18 },
  modeList: { marginTop: 9, gap: 8 },
  modeCard: {
    minHeight: 55,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modeCardSelected: { borderColor: colors.goldDark, backgroundColor: colors.surfaceStrong },
  radio: {
    width: 17,
    height: 17,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioSelected: { borderColor: colors.magenta },
  radioDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.magenta },
  modeCopy: { flex: 1, marginLeft: 10 },
  modeText: {
    fontFamily: fontFamilyMedium,
    color: colors.inkSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  modeTextSelected: { color: colors.ink, fontWeight: '800' },
  modeTag: { fontFamily, color: colors.inkMuted, fontSize: 8, marginTop: 2 },
  modeLine: { width: 22, height: 2, backgroundColor: colors.border },
  modeLineSelected: { backgroundColor: colors.goldDark },
  errorBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 9,
    backgroundColor: '#E8C1D3',
    borderWidth: 1,
    borderColor: '#B45D83',
  },
  errorTitle: {
    fontFamily: fontFamilyMedium,
    color: colors.danger,
    fontSize: 10,
    fontWeight: '800',
  },
  errorText: { fontFamily, color: colors.danger, fontSize: 10, lineHeight: 15, marginTop: 3 },
  button: { marginTop: 16 },
  saveProgress: { marginTop: 10 },
});
