import { StyleSheet } from 'react-native';
import { isDemoMode } from '../../data/runtime';
import { colors, fontFamily, fontFamilyMedium } from '../../ui';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  list: { paddingHorizontal: 18, paddingBottom: 28 },
  fullHeader: { paddingTop: 18, paddingBottom: 12 },
  headerControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  streamBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 9,
    minHeight: 28,
    borderWidth: 1,
    borderColor: isDemoMode ? colors.border : 'rgba(236,217,167,0.48)',
    borderRadius: isDemoMode ? 6 : 7,
    backgroundColor: isDemoMode ? colors.surface : 'rgba(92,15,66,0.62)',
  },
  streamDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.gold },
  streamText: {
    fontFamily: fontFamilyMedium,
    color: isDemoMode ? colors.ink : colors.lightText,
    fontSize: 8,
    fontWeight: isDemoMode ? '700' : '800',
    letterSpacing: isDemoMode ? 0.65 : 1.15,
  },
  archiveButton: { alignItems: 'flex-end', paddingVertical: 4 },
  archiveButtonText: {
    fontFamily: fontFamilyMedium,
    color: isDemoMode ? colors.ink : colors.lightText,
    fontSize: 11,
    fontWeight: '800',
  },
  archiveLine: { width: 52, height: 2, backgroundColor: colors.gold, marginTop: 5 },
  topicSection: { marginTop: 15 },
  topicSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  topicSectionMeta: {
    flexShrink: 1,
    fontFamily,
    color: isDemoMode ? colors.inkMuted : '#D9AFC5',
    fontSize: 8,
    textAlign: 'right',
  },
  filtersRow: { marginTop: 15 },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 8 },
  errorBox: {
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: isDemoMode ? '#D9A39A' : '#B85A83',
    borderRadius: 9,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  errorText: { flex: 1, fontFamily, color: colors.danger, fontSize: 11 },
  retryText: {
    fontFamily: fontFamilyMedium,
    color: colors.ink,
    fontSize: 11,
    fontWeight: '800',
  },
  loadingBox: { minHeight: 260 },
  compactPanel: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 0,
    zIndex: 50,
    elevation: 15,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 9,
    borderRadius: isDemoMode ? 8 : 12,
    borderWidth: 1,
    borderColor: isDemoMode ? colors.borderStrong : 'rgba(236,217,167,0.48)',
    backgroundColor: isDemoMode ? colors.surface : 'rgba(61,6,43,0.97)',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: isDemoMode ? 0.03 : 0.28,
    shadowRadius: 18,
  },
  compactTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  compactTitle: {
    fontFamily: fontFamilyMedium,
    color: isDemoMode ? colors.ink : colors.lightText,
    fontSize: 14,
    fontWeight: '800',
  },
  compactArchive: {
    fontFamily: fontFamilyMedium,
    color: isDemoMode ? colors.goldDark : colors.goldSoft,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  compactFilters: { flexDirection: 'row', gap: 5, marginTop: 5 },
  empty: {
    minHeight: 230,
    justifyContent: 'center',
    padding: 28,
    borderRadius: isDemoMode ? 10 : 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  emptyGold: { width: 42, height: 2, backgroundColor: colors.gold, marginBottom: 13 },
  emptyKicker: {
    fontFamily: fontFamilyMedium,
    color: isDemoMode ? colors.goldDark : colors.magenta,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  emptyTitle: {
    fontFamily: fontFamilyMedium,
    color: colors.ink,
    fontSize: 19,
    fontWeight: '800',
    marginTop: 7,
  },
  emptyText: { fontFamily, color: colors.inkSoft, marginTop: 7, fontSize: 12, lineHeight: 18 },
  footerArchive: {
    marginTop: 4,
    marginBottom: 18,
    padding: 16,
    borderRadius: 11,
    backgroundColor: isDemoMode ? colors.surface : '#5A0D42',
    borderWidth: 1,
    borderColor: isDemoMode ? colors.borderStrong : 'rgba(236,217,167,0.42)',
  },
  footerArchiveRule: { width: 42, height: 2, backgroundColor: colors.gold, marginBottom: 10 },
  footerArchiveTitle: {
    fontFamily: fontFamilyMedium,
    color: isDemoMode ? colors.ink : colors.lightText,
    fontSize: 14,
    fontWeight: '800',
  },
  footerArchiveMeta: {
    fontFamily,
    color: isDemoMode ? colors.inkMuted : '#D9AFC5',
    fontSize: 10,
    marginTop: 3,
  },
});
